.PHONY: install-musescore

install-musescore:
	rm -rf ../data/musescore.AppImage
	wget https://github.com/musescore/MuseScore/releases/download/v3.6.2/MuseScore-3.6.2.548021370-x86_64.AppImage
	mv MuseScore-3.6.2.548021370-x86_64.AppImage ../data/musescore.AppImage
	chmod +x ../data/musescore.AppImage
